// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoNidP2ZHeV1BlHahGd46CE0M_rWeJUfA',
    appId: '1:290208990981:web:7afd09443c3edd2f77996c',
    messagingSenderId: '290208990981',
    projectId: 'todo-a8087',
    authDomain: 'todo-a8087.firebaseapp.com',
    storageBucket: 'todo-a8087.firebasestorage.app',
    measurementId: 'G-KPKVRMYFLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyR7WRY_nnlgzLd__yEDx1eStNulwTUyc',
    appId: '1:290208990981:android:7e778d28ad6da56377996c',
    messagingSenderId: '290208990981',
    projectId: 'todo-a8087',
    storageBucket: 'todo-a8087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiEbNlqB95gWLkH8To7KLi5LqxJb8y-_U',
    appId: '1:290208990981:ios:b9c21ca124f777e677996c',
    messagingSenderId: '290208990981',
    projectId: 'todo-a8087',
    storageBucket: 'todo-a8087.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoNidP2ZHeV1BlHahGd46CE0M_rWeJUfA',
    appId: '1:290208990981:web:4fa5bb23e580172177996c',
    messagingSenderId: '290208990981',
    projectId: 'todo-a8087',
    authDomain: 'todo-a8087.firebaseapp.com',
    storageBucket: 'todo-a8087.firebasestorage.app',
    measurementId: 'G-G2ZJK4RGTS',
  );
}
